### ISSUE TITLE
Turtles not finding and going to home

### ISSUE THREAD

**Issue by RnK-BnK** [merlinlikethewizard/Mastermine#2]
When I place the turtles and give them fuel and the code they just move forward and back one block and then just stay there, I can move them manually but when I try to use the return command it just loops "directive: go_to_hold" and stands still, I'm sure I followed everything correctly, do you know how to fix this?

**Comment by merlinlikethewizard** [comment]
Hmm, that's not supposed to happen (obviously). Debugging here is tricky because I can't ask for log data, but let's try some things. First, can you go through all the tabs on both the turtle and hub and see if any of the threads have errors? Barring that, can you check what state the turtle is in, and if the whosmine program on the hub is sending directives? I don't know if you're playing on a server but I'm happy to log on and help if needed.

**Comment by RnK-BnK** [comment]
I managed to get it working by moving the computer arorn and it seemed to work, maybe i had it too close to the GPS because i had it right next to it, the status of the turtles was in the wait mode, none of the threads had any errors, just the go home command being repeated a lot

**Comment by RnK-BnK** [comment]
o sorry i missed a typo, it looped directive: go_to_home not directive: go_to_hold

**Comment by merlinlikethewizard** [comment]
That's great! Glad you got it to work. Hearing how you solved the problem it's possible your turtles were too far away from the mine entrance. If they aren't within 8 blocks of the center while above ground they get confused.

**Comment by merlinlikethewizard** [comment]
Anyway, sounds like you got it working! Lemme know if you have similar issues.
