### ISSUE TITLE
hiya, slight issue with the turtles mining

### ISSUE THREAD

**Issue by deepfriedpineapl** [merlinlikethewizard/Mastermine#22]
### MY BACKGROUND
I'm not a super skilled programmer and I don't know much nor fully understand lua but I do have backgrounds in python, html/css/javascript kinda deal. I'm not super skilled and programing isn't super my thing so I'm a bit rusty but I understand some basic concepts

### MY SETUP
I'm using Minecraft 1.16.5 with Optifine among other mods including CC:tweaked and advanced utilities for the chunky turtles. I'm on a server I run and have access to the files of said server

### THE ERRORS
I can setup the turtles, edit their home position, the hub; chest; and turtles all function as they're supposed to... until they try to actually mine. every time I toggle the power they go into the mine, start to try to strip mine but the "whosmineisitanyway" tab always crashes and for seemingly different reasons each time. 

- one error I got was "actions:608: attempt to index field 'blocktags' (a nil value)"

- another time it got the command "pass" from the hub and then immediately after crashed with no error message

- some don't even mine, some just sit there staring at the stone and not trying to mine

_Let me know if you need any more info or if you want you can try to connect to the server to check the turtles out in person, I'd rather DM you the details on that however_

**Comment by PanGeo-Code** [comment]
i have got the same issue

**Comment by merlinlikethewizard** [comment]
Interesting issue. I tried with a fresh install of forge & mods and wasn't able to reproduce it. Are you using forge? If not that might be where the difference is (not that you should need to).

It seems like the problem is with the ore-detecting code in the turtles. Right now one of the ways they scan for ore is by checking the "blocktags" on each block to see if they've been tagged as ore. It looks like for whatever reason the data your turtles are retrieving from the blocks doesn't contain a "blocktags" field. I'm not quite sure how they work (that code was added by another user), but a quick band-aid fix is to just ignore the block if it doesn't have a blocktags field. So I updated the code to do that. It's all in the actions.lua file so if you just swap that one in it should fix that particular problem.

If there are still issues I'd be happy to come take a look on the server. I've been traveling recently and haven't had time to visit all the servers I planned to but I'm MerlinLikeTheWizard#9300 on discord if you want to message.

**Comment by deepfriedpineapl** [comment]
that's perfect, works like a charm (at least in my single player testing world. we'll see how they do on a server). i'll let you know if i have any more issues with the system
